spring.application.name=crud-api

spring.datasource.url=jdbc:postgresql://ep-solitary-paper-ad5yxlg5-pooler.c-2.us-east-1.aws.neon.tech
spring.datasource.username=neondb_owner
spring.datasource.password=npg_yuC0bk2BeIXt

spring.jpa.hibernate.ddl-auto=update

# Log out sql queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE